### PR TITLE
feat: config path to panel on redirect if empty auth

### PR DESCRIPTION
**Pull request by dennisbaum**
like said it would be nice to config the redirect if auth is empty by KIRBY_PANEL_SLUG

### CODE REVIEW

**Comment by johannschopplich** [comment]
Great idea. I'd prefer a less verbose version:

```php
go(option('panel.slug'));
```

Since we already declare the Panel slug in:
https://github.com/johannschopplich/kirby-headless-starter/blob/7efeeb971ddf398779d85b0d358e9a860a793cf2/site/config/config.php#L9

**Comment by dennisbaum** [comment]
you're right. 
so the fallback is already done in the config

**Comment by dennisbaum** [comment]
i have updated the redirect.
also replaced public/media/index.html with .gitkeep. 
i was always wondering, why kirby adds empty folders to git by index.html.
i think you replaced all, but media...

**Comment by johannschopplich** [comment]
The `index.html` is to prevent Apache/Nginx to fire up their error page and instead display a blank page. I typically use the public folder setup, thus, no directory will be served and accessible publicly anyway. Except for `media`. It's containing `index.html` is there on purpose for a direct visit of `media`. 

Please revert the `.gitkeep` change (should've been a separate PR anyway. 😉 ).

**Comment by dennisbaum** [comment]
i reverted the .gitkeep commit.
sorry for the circumstances and thank you for the clarification.

**Comment by johannschopplich** [comment]
Great, thanks!

**Pull request merged**
